import { useEffect,useMemo,useRef,useState } from 'react';
import { convertFileSrc } from '@tauri-apps/api/core';
import { save } from '@tauri-apps/plugin-dialog';
import ReactMarkdown,{defaultUrlTransform} from 'react-markdown';
import { ArrowLeft,Download,Edit3,Save,Search,Volume2,ExternalLink,Quote,Sparkles,NotebookPen,ChevronDown,History } from 'lucide-react';
import { api,errorMessage } from '../api';
import type { AssetDetail,AppSettings,Citation,Note,Segment,Transcript } from '../types';
import { citationTarget,durationLabel,safeFilename,selectedText,sourceAt,sourceLabel,timeLabel } from '../utils';
import { Empty,Modal,Spinner,useConfirm } from './Common';
import IntegrityPanel from './IntegrityPanel';
import './ReaderQuality.css';
import { readerVersionAfterRefresh } from './readerQuality';

function NoteBody({note,onCitation,onError}:{note:Note;onCitation:(citation:Citation)=>void;onError:(error:string)=>void}) {
  const content=note.content.replace(/\[引用:([^\]]+)\]/g,(original,id:string)=>{
    const cite=note.citations.find(c=>c.segmentId===id);return cite?`[${timeLabel(cite.startMs)}](#citation-${encodeURIComponent(id)})`:original;
  });
  return <div className="markdown"><ReactMarkdown skipHtml urlTransform={url=>defaultUrlTransform(url)} components={{
    a:({href,children})=><a href={href} onClick={e=>{e.preventDefault();if(href?.startsWith('#citation-')){const cite=note.citations.find(c=>c.segmentId===decodeURIComponent(href.slice(10)));if(cite)onCitation(cite);}else if(href)void api.openExternal(href).catch(e=>onError(errorMessage(e)));}}>{children}</a>,
    img:()=>null,
  }}>{content}</ReactMarkdown></div>;
}

export default function Reader({detail,settings,apiKeyConfigured,onBack,onChanged,onSettings,onDirty,onError,initialJump}:{detail:AssetDetail;settings:AppSettings;apiKeyConfigured:boolean;onBack:()=>void;onChanged:()=>Promise<void>;onSettings:()=>void;onDirty:(dirty:boolean)=>void;onError:(error:string)=>void;initialJump?:{transcriptId:string;segmentId:string}|null}) {
  const [viewId,setViewId]=useState(initialJump?.transcriptId??detail.transcript?.id??''),[editing,setEditing]=useState(false),[draft,setDraft]=useState<Segment[]>([]),[editBase,setEditBase]=useState('');
  const [selected,setSelected]=useState(new Set<string>()),[filter,setFilter]=useState(''),[visible,setVisible]=useState(250),[highlight,setHighlight]=useState(initialJump?.segmentId??''),[busy,setBusy]=useState('');
  const [noteMode,setNoteMode]=useState<'saved'|'manual'|'ai'>('saved'),[noteTitle,setNoteTitle]=useState(''),[noteContent,setNoteContent]=useState(''),[kind,setKind]=useState('summary'),[question,setQuestion]=useState('');
  const [exporting,setExporting]=useState(false),[format,setFormat]=useState('md'),[destination,setDestination]=useState('');
  const [reviewDirty,setReviewDirty]=useState(false),[reviewEpoch,setReviewEpoch]=useState(0),[vaultFeedback,setVaultFeedback]=useState('');
  const [aux,setAux]=useState<'notes'|'quality'|null>(()=>{try{const saved=localStorage.getItem('reader.aux');return saved==='notes'||saved==='quality'?saved:null;}catch{return null;}}),[excerpt,setExcerpt]=useState(false),[historyOpen,setHistoryOpen]=useState(false),[qualityBusy,setQualityBusy]=useState(false),[qualityText,setQualityText]=useState('正在检查文字时间轴');
  useEffect(()=>{try{localStorage.setItem('reader.aux',aux??'closed');}catch{}},[aux]);
  const audio=useRef<HTMLAudioElement>(null),list=useRef<HTMLDivElement>(null);const {confirm,dialog}=useConfirm();
  useEffect(()=>{
    const closeMore=(event:KeyboardEvent|PointerEvent)=>{
      const menu=document.querySelector<HTMLDetailsElement>('.reader-more[open]');
      if(!menu)return;
      if(event instanceof KeyboardEvent){if(event.key!=='Escape')return;menu.open=false;menu.querySelector('summary')?.focus();}
      else if(!menu.contains(event.target as Node))menu.open=false;
    };
    document.addEventListener('keydown',closeMore);document.addEventListener('pointerdown',closeMore);
    return()=>{document.removeEventListener('keydown',closeMore);document.removeEventListener('pointerdown',closeMore);};
  },[]);
  const view=detail.versions.find(v=>v.id===viewId)??detail.transcript;
  const displayed=editing?draft:view?.segments??[];
  const dirty=editing&&draft.some((s,i)=>s.text!==detail.versions.find(v=>v.id===editBase)?.segments[i]?.text);
  const scope=useMemo(()=>selectedText(displayed,selected),[displayed,selected]);
  const filtered=useMemo(()=>displayed.filter(s=>s.text.toLocaleLowerCase().includes(filter.toLocaleLowerCase())),[displayed,filter]);
  const unsaved=reviewDirty||dirty||!!noteTitle.trim()||!!noteContent.trim();
  useEffect(()=>{onDirty(unsaved);return()=>onDirty(false);},[unsaved,onDirty]);
  useEffect(()=>{setViewId(current=>readerVersionAfterRefresh(current,detail.transcript?.id??null));},[detail.transcript?.id]);
  useEffect(()=>{setSelected(new Set());setExcerpt(false);setVisible(250);},[viewId]);
  useEffect(()=>{if(initialJump){setViewId(initialJump.transcriptId);setHighlight(initialJump.segmentId);}},[initialJump]);
  useEffect(()=>{
    if(!highlight)return;const index=filtered.findIndex(s=>s.id===highlight);if(index<0)return;
    if(index>=visible){setVisible(index+50);return;}
    const timeout=setTimeout(()=>list.current?.querySelector(`[data-segment-id="${CSS.escape(highlight)}"]`)?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'}),50);
    return()=>clearTimeout(timeout);
  },[highlight,viewId,visible,filtered]);
  async function guarded(action:()=>void){if(qualityBusy){onError('请等待核对任务完成，或先取消任务。');return;}if(unsaved&&!(await confirm('有尚未保存的校对、笔记或核对结论。继续后会放弃这些修改。')))return;setEditing(false);setNoteTitle('');setNoteContent('');setReviewEpoch(n=>n+1);action();}
  async function changeVersion(id:string){await guarded(()=>{setViewId(id);setFilter('');});}
  async function persistEdit(){if(!view)return;setBusy('保存修订版本');try{const version=await api.saveEdit(detail.asset.id,editBase,draft);setEditing(false);setViewId(version.id);await onChanged();}catch(e){onError(errorMessage(e));}finally{setBusy('');}}
  async function activate(){if(!view)return;setBusy('切换版本');try{await api.activateVersion(detail.asset.id,view.id);await onChanged();}catch(e){onError(errorMessage(e));}finally{setBusy('');}}
  async function play(segment:Segment){setHighlight(segment.id);if(audio.current&&detail.asset.audioPath){audio.current.currentTime=segment.startMs/1000;try{await audio.current.play();}catch(e){onError(errorMessage(e));}}else{const url=sourceAt(detail.asset,segment.startMs);if(url)try{await api.openExternal(url);}catch(e){onError(errorMessage(e));}}}
  async function jump(note:Note,citation:Citation){const target=citationTarget(detail.versions,note.transcriptId,citation);if(!target){onError('这条引用对应的原文版本不可用。');return;}await guarded(()=>{setViewId(target.version.id);setFilter('');setHighlight(target.segment.id);});}
  async function getAudio(){setBusy('添加回听任务');try{await api.ensureAudio(detail.asset.id);await onChanged();}catch(e){onError(errorMessage(e));}finally{setBusy('');}}
  async function saveNote(){if(!view)return;setBusy('保存笔记');try{await api.saveManualNote(detail.asset.id,view.id,noteTitle,noteContent,scope.segments.map(s=>s.id));setNoteTitle('');setNoteContent('');setNoteMode('saved');await onChanged();}catch(e){onError(errorMessage(e));}finally{setBusy('');}}
  async function generate(){if(!view)return;setBusy(kind==='answer'?'正在根据所选片段回答':'正在整理所选片段');try{await api.generateKnowledge(detail.asset.id,view.id,kind,kind==='answer'?question:null,scope.segments.map(s=>s.id));setNoteMode('saved');await onChanged();}catch(e){onError(errorMessage(e));}finally{setBusy('');}}
  function startExport(){if(!view)return;setDestination(`${settings.dataDir.replace(/[\\/]$/,'')}/exports/${safeFilename(detail.asset.title)}-v${view.version}.${format}`);setExporting(true);}
  async function pickExport(){try{const path=await save({defaultPath:destination,filters:[{name:format.toUpperCase(),extensions:[format]}]});if(path)setDestination(path);}catch(e){onError(errorMessage(e));}}
  async function exportNow(){if(!view)return;setBusy('导出文件');try{await api.exportAsset(detail.asset.id,format,destination,view.id);setExporting(false);onError(`已导出：${destination}`);}catch(e){onError(errorMessage(e));}finally{setBusy('');}}
  async function syncVault(){if(!view)return;if(!settings.obsidianVault){onSettings();return;}if(unsaved){onError('请先保存校对、笔记与核对结论，再同步。');return;}setBusy('同步本地知识库');setVaultFeedback('');try{const result=await api.syncVault(detail.asset.id,view.id);setVaultFeedback(`${result.created?'已创建快照':'此快照已同步，无需重复写入'}：${result.snapshotPath}`);}catch(e){onError(errorMessage(e));}finally{setBusy('');}}
  async function retranscribe(){if(unsaved){onError('请先保存未完成的编辑。');return;}if(!(await confirm('按当前识别设置重新处理此课程，完成后生成独立文字版本；原文与历史笔记保留。继续？')))return;setBusy('添加重新转写任务');try{await api.createJobs(detail.asset.source,[detail.asset.page??1],'transcribe');await onChanged();}catch(e){onError(errorMessage(e));}finally{setBusy('');}}
  function seekIssue(ms:number){setFilter('');const target=view?.segments.find(s=>s.endMs>=ms)??view?.segments.at(-1);if(target)void play({...target,startMs:ms});}
  async function adopted(version:Transcript){await onChanged();setViewId(version.id);setSelected(new Set());setFilter('');}
  const active=view?.id===detail.asset.activeVersionId;
  const remoteSource=Boolean(sourceAt(detail.asset,0));
  const endpoint=(()=>{try{return new URL(settings.llmBaseUrl).host;}catch{return settings.llmBaseUrl;}})();
  return <div className="reader">
    <header className="reader-heading"><div className="reader-title"><button className="icon-button" aria-label="返回资料库" onClick={onBack}><ArrowLeft size={19}/></button><div><span className="eyebrow">{sourceLabel(detail.asset)} · {durationLabel(detail.asset.durationMs)}</span><h1 title={detail.asset.title}>{detail.asset.title}</h1></div></div><div className="actions reader-main-actions"><button aria-expanded={aux==='notes'} onClick={()=>setAux(aux==='notes'?null:'notes')}><NotebookPen size={16}/>笔记</button><details className="reader-more"><summary>更多</summary><div className="reader-more-items" onClick={e=>{if((e.target as HTMLElement).closest('button:not(:disabled)')){const menu=e.currentTarget.closest('details');if(menu)menu.open=false;}}}><button disabled={!view||dirty||!!busy||qualityBusy} onClick={startExport}><Download size={16}/>导出资料</button><button disabled={!view||unsaved||!!busy} onClick={()=>void syncVault()}>同步到 Obsidian</button><button disabled={!view||qualityBusy} onClick={()=>setHistoryOpen(v=>!v)}><History size={16}/>历史版本</button></div></details></div></header>
    <div className="reader-layout"><section className="transcript-pane" aria-label="文字稿">
      <div className="transcript-toolbar"><div className="actions"><strong>文字稿</strong>{view&&historyOpen&&<select aria-label="文字版本" value={view.id} disabled={editing||!!busy||qualityBusy} onChange={e=>void changeVersion(e.target.value)}>{detail.versions.map(version=><option key={version.id} value={version.id}>版本 {version.version}{version.isActive?' · 当前':''}{version.sourceKind==='edited'?' · 校对':''}</option>)}</select>}</div><div className="actions">{view&&!active&&<button disabled={!!busy||unsaved||qualityBusy} onClick={()=>void activate()}><History size={14}/>设为当前版本</button>}{view&&active&&!editing&&<button className="quiet" disabled={!!busy||reviewDirty||qualityBusy} onClick={()=>{setDraft(view.segments.map(s=>({...s})));setEditBase(view.id);setEditing(true);}}><Edit3 size={15}/>校对</button>}{editing&&<><button disabled={!!busy} onClick={()=>void guarded(()=>{})}>放弃修改</button><button className="primary" disabled={!dirty||!!busy} onClick={()=>void persistEdit()}><Save size={15}/>保存新版本</button></>}</div></div>
      {view&&<button className="quality-summary" aria-expanded={aux==='quality'} onClick={()=>setAux(aux==='quality'?null:'quality')}>{qualityText}<ChevronDown size={14}/></button>}
      {vaultFeedback&&<div className="vault-feedback">{vaultFeedback}<button onClick={()=>void api.openVaultNote(detail.asset.id).catch(e=>onError(errorMessage(e)))}>在 Obsidian 打开课程</button></div>}
      {!active&&view&&<div className="version-notice">正在查看历史版本 {view.version}，引用保持与当时原文一致。</div>}
      {detail.asset.audioPath?<div className="audio-bar"><Volume2 size={18}/><audio ref={audio} controls preload="metadata" src={convertFileSrc(detail.asset.audioPath)} aria-label="课程回听"/><button className="icon-button" title="后退 5 秒" aria-label="后退 5 秒" onClick={()=>{if(audio.current)audio.current.currentTime=Math.max(0,audio.current.currentTime-5);}}>−5s</button></div>:<div className="audio-empty"><ExternalLink size={15}/><span>{remoteSource?(detail.asset.bvid?'点击时间戳可回到原视频。':'点击时间戳可打开原网页，部分网站支持时间定位。'):detail.asset.sourceKind==='subtitle'?'字幕文件未包含音频，目前仅能检查文字时间轴。':'尚无本地回听音频。'}</span>{detail.asset.sourceKind!=='subtitle'&&<button className="text-button" disabled={!!busy||qualityBusy} onClick={()=>void getAudio()}>获取本地回听音频</button>}</div>}
      {view?<><div className="text-tools"><div className="small-search"><Search size={15}/><input aria-label="搜索当前文字稿" placeholder="查找原文…" value={filter} onChange={e=>{setFilter(e.target.value);setVisible(250);}}/></div><span className="muted">{filtered.length} 个片段</span><button className="text-button" aria-pressed={excerpt} onClick={()=>{setExcerpt(!excerpt);if(excerpt)setSelected(new Set());}}>{excerpt?'退出摘录并清空选择':'摘录 / 选择片段'}</button></div>
      {excerpt&&<div className="selection-bar"><label><input type="checkbox" aria-label="选择全部原文片段" checked={displayed.length>0&&selected.size===displayed.length} onChange={()=>setSelected(selected.size===displayed.length?new Set():new Set(displayed.map(s=>s.id)))}/>全部片段</label><span>已选 {scope.segments.length} 段 · {scope.chars.toLocaleString()} 字符</span>{!!selected.size&&<button className="text-button" onClick={()=>setSelected(new Set())}>清空</button>}</div>}
      <div className="segments" ref={list}>{filtered.slice(0,visible).map(segment=><div className={`segment ${selected.has(segment.id)?'selected':''} ${highlight===segment.id?'highlighted':''}`} key={segment.id} data-segment-id={segment.id}>
        {excerpt&&<input type="checkbox" aria-label={`选择 ${timeLabel(segment.startMs)} 的片段`} checked={selected.has(segment.id)} onChange={()=>setSelected(current=>{const next=new Set(current);next.has(segment.id)?next.delete(segment.id):next.add(segment.id);return next;})}/>}
        <button className="timestamp" title={detail.asset.audioPath?'回听此处':remoteSource?'打开原视频':'片段起始时间'} onClick={()=>void play(segment)}>{timeLabel(segment.startMs)}</button>
        {editing?<textarea disabled={!!busy} aria-label={`校对 ${timeLabel(segment.startMs)} 的文字`} rows={Math.max(2,Math.ceil(segment.text.length/50))} value={segment.text} onChange={e=>setDraft(current=>current.map(s=>s.id===segment.id?{...s,text:e.target.value}:s))}/>:<p>{segment.text}</p>}
      </div>)}{!filtered.length&&<p className="inline-empty">没有找到匹配的原文。</p>}{filtered.length>visible&&<button className="load-more" onClick={()=>setVisible(n=>n+250)}><ChevronDown size={16}/>再显示 250 个片段（剩余 {filtered.length-visible}）</button>}</div></>:<Empty title="文字稿正在准备">处理完成后，原文、时间戳和可编辑版本会显示在这里。</Empty>}
      {busy&&<div className="reader-busy"><Spinner label={busy}/></div>}
    </section><aside className="notes-pane reader-aux" hidden={!aux} aria-label={aux==='quality'?'转录质量核对':'课程笔记'}><div className="notes-heading"><div className="actions"><button aria-pressed={aux==='notes'} onClick={()=>setAux('notes')}>笔记</button><button aria-pressed={aux==='quality'} onClick={()=>setAux('quality')}>核对</button></div><button className="text-button" onClick={()=>setAux(null)}>收起</button></div>
      <div className="reader-quality-body" hidden={aux!=='quality'}>{view&&<IntegrityPanel key={`${view.id}-${reviewEpoch}`} assetId={detail.asset.id} transcriptId={view.id} durationMs={detail.asset.durationMs} audioPath={detail.asset.audioPath} disabled={editing||!!busy} canRetranscribe={detail.asset.sourceKind!=='subtitle'} canAdopt={active&&!editing&&!noteTitle.trim()&&!noteContent.trim()} onSeek={seekIssue} onRetranscribe={()=>void retranscribe()} onDirty={setReviewDirty} onBusy={setQualityBusy} onSummary={setQualityText} onAdopted={adopted} onGetAudio={detail.asset.sourceKind!=='subtitle'?()=>void getAudio():undefined}/>}</div>
      <div className="reader-notes-content" hidden={aux!=='notes'}>
      <div className="note-tabs" role="tablist" aria-label="笔记工具">{[['saved','已保存'],['manual','写笔记'],['ai','AI 整理']].map(([id,label])=><button role="tab" aria-selected={noteMode===id} className={noteMode===id?'active':''} key={id} onClick={()=>setNoteMode(id as typeof noteMode)}>{label}</button>)}</div>
      <div className="notes-body">{noteMode==='saved'?(detail.notes.length?detail.notes.map(note=><article className="note" key={note.id}><div className="note-meta"><span>{note.kind==='manual'?'手写 / 摘录':note.kind==='answer'?'课程问答':'AI 学习笔记'}</span><span>{new Date(note.createdAt).toLocaleDateString('zh-CN')}</span></div><h3>{note.title}</h3>{note.stale&&<div className="stale-note">原文已更新 · 保留旧版引用，可重新整理。</div>}<NoteBody note={note} onCitation={citation=>void jump(note,citation)} onError={onError}/>{note.citations.length>0&&<details className="citations" open={note.citations.length<=4}><summary><Quote size={13}/>{note.citations.length} 处原文依据</summary>{note.citations.map(citation=><button key={citation.segmentId} onClick={()=>void jump(note,citation)}><span className="mono">{timeLabel(citation.startMs)}</span><span>{citation.text}</span></button>)}</details>}</article>):<div className="notes-empty"><NotebookPen size={25}/><h3>把理解留在课程旁</h3><p>点击「摘录 / 选择片段」选择原文，写一条笔记或整理带出处的学习材料。</p><button onClick={()=>setNoteMode('manual')}>写第一条笔记</button></div>):null}
      {noteMode==='manual'&&<div className="note-composer"><p className="hint">保存时绑定所查看的文字版本，并引用已选的 {scope.segments.length} 个片段。</p><label className="field">标题<input disabled={!!busy} value={noteTitle} onChange={e=>setNoteTitle(e.target.value)} placeholder="这一节的理解与疑问"/></label><label className="field">笔记内容<textarea disabled={!!busy} rows={12} value={noteContent} onChange={e=>setNoteContent(e.target.value)} placeholder="记录你的理解、待解决的问题，或摘录选中的文字。支持 Markdown。"/></label><button className="quiet" disabled={!scope.segments.length} onClick={()=>{setNoteContent(scope.segments.map(s=>`> ${s.text.replace(/\n/g,'\n> ')}\n\n[引用:${s.id}]`).join('\n\n'));if(!noteTitle)setNoteTitle('课堂摘录');}}><Quote size={15}/>摘录所选文字</button><button className="primary full-width" disabled={!view||!noteContent.trim()||!!busy||dirty} onClick={()=>void saveNote()}><Save size={16}/>保存笔记</button>{dirty&&<p className="hint">请先保存校对内容。</p>}</div>}
      {noteMode==='ai'&&<div className="note-composer">{!excerpt&&<button onClick={()=>setExcerpt(true)}>选择要整理的片段</button>}<div className="ai-scope"><Sparkles size={18}/><div><strong>基于选定原文整理</strong><p>{scope.segments.length} 个片段 · {scope.chars.toLocaleString()} 字符</p></div></div>{!settings.llmModel?<div className="setup-note"><p>先配置一个 OpenAI 兼容文本接口，也可使用本机服务。</p><button onClick={onSettings}>配置 API</button></div>:<><p className="hint">将发送以上文字到 {endpoint}，不包含音视频和 Cookie。</p><label className="field">整理方式<select value={kind} onChange={e=>setKind(e.target.value)}><option value="summary">摘要、提纲、关键概念与学习笔记</option><option value="answer">单课程问答</option></select></label>{kind==='answer'&&<label className="field">你的问题<textarea rows={4} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="这节课如何解释……？"/></label>}<p className="hint">模型：{settings.llmModel} · 单次上限 {settings.llmContextChars.toLocaleString()} 字符{!apiKeyConfigured?' · 未保存密钥':''}</p>{scope.chars>settings.llmContextChars&&<p className="error-text">所选文字超出上限，请减少选择。</p>}{!active&&<p className="hint">AI 整理使用当前版本，请先返回当前文字版本。</p>}<button className="primary full-width" disabled={!scope.segments.length||scope.chars>settings.llmContextChars||!!busy||dirty||!active||(kind==='answer'&&!question.trim())} onClick={()=>void generate()}><Sparkles size={16}/>{kind==='answer'?'根据原文回答':'生成学习笔记'}</button></>}</div>}
      </div></div></aside></div>
    {exporting&&<Modal title="导出资料" onClose={()=>{if(!busy)setExporting(false);}}><div className="modal-content"><p className="hint">导出文字版本 {view?.version}；Markdown 同时包含绑定此版本的笔记和引用。</p><label className="field">文件格式<select value={format} onChange={e=>{setFormat(e.target.value);setDestination(path=>path.replace(/\.[^.\\/]+$/,`.${e.target.value}`));}}><option value="md">Markdown · 文字与笔记</option><option value="txt">TXT · 纯文字</option><option value="srt">SRT · 时间轴字幕</option><option value="vtt">WebVTT · 网页字幕</option></select></label><label className="field">保存路径<input value={destination} onChange={e=>setDestination(e.target.value)}/></label><button onClick={()=>void pickExport()}>选择保存位置</button></div><footer><button onClick={()=>setExporting(false)} disabled={!!busy}>取消</button><button className="primary" disabled={!!busy||!destination} onClick={()=>void exportNow()}><Download size={16}/>导出</button></footer></Modal>}{dialog}
  </div>;
}
