import { useEffect,useState } from 'react';
import { open } from '@tauri-apps/plugin-dialog';
import { Cpu,FolderOpen,RefreshCw,Download,Save,Trash2,FlaskConical,KeyRound,HardDrive,CheckCircle2,ExternalLink } from 'lucide-react';
import { api,errorMessage } from '../api';
import type { AppSettings,Asset,SystemResources,ResourceRecommendation,ResourceReport,BenchmarkRecord,CacheCategory } from '../types';
import { bytesLabel } from '../utils';
import { Spinner,useConfirm } from './Common';
import {applyTheme,themes} from '../theme';

const models=[['tiny','约 75 MB'],['base','约 142 MB'],['small','约 462 MB'],['medium','约 1.5 GB'],['large-v3','约 3 GB'],['turbo','约 1.6 GB']];
type Props={settings:AppSettings;assets:Asset[];resources:SystemResources;recommendation:ResourceRecommendation;apiKeyConfigured:boolean;onSaved:()=>Promise<void>;onDirty:(dirty:boolean)=>void;onError:(message:string)=>void};
export default function SettingsPanel({settings,assets,resources,recommendation,apiKeyConfigured,onSaved,onDirty,onError}:Props){
  const [form,setForm]=useState(settings),[section,setSection]=useState('storage'),[busy,setBusy]=useState(''),[key,setKey]=useState(''),[feedback,setFeedback]=useState('');
  const [report,setReport]=useState<ResourceReport|null>(null),[benchmarks,setBenchmarks]=useState<BenchmarkRecord[]>([]),[cache,setCache]=useState<CacheCategory[]>([]),[sample,setSample]=useState(assets.find(a=>a.audioPath)?.id??'');
  const {confirm,dialog}=useConfirm();
  useEffect(()=>{applyTheme(form.theme);return()=>applyTheme(settings.theme);},[form.theme,settings.theme]);
  const settingsKey=JSON.stringify(settings);
  useEffect(()=>{setForm(settings);setReport(null);},[settingsKey]);
  useEffect(()=>{let current=true;void Promise.all([api.listBenchmarks(),api.cacheInventory()]).then(([runs,categories])=>{if(current){setBenchmarks(runs);setCache(categories);}}).catch(e=>{if(current)onError(errorMessage(e));});return()=>{current=false;};},[settings.dataDir,settings.modelDir,onError]);
  const actual=report?.resources??resources,choice=report?.recommendation??recommendation;
  const changed=JSON.stringify(form)!==settingsKey;
  useEffect(()=>{onDirty(changed||!!key);return()=>onDirty(false);},[changed,key,onDirty]);
  function update<K extends keyof AppSettings>(key:K,value:AppSettings[K]){setForm(current=>({...current,[key]:value}));setFeedback('');}
  async function operation(label:string,fn:()=>Promise<void>){setBusy(label);setFeedback('');try{await fn();}catch(e){onError(errorMessage(e));}finally{setBusy('');}}
  async function choose(field:keyof AppSettings,directory=false){try{const value=await open({multiple:false,directory});if(typeof value==='string')update(field,value as never);}catch(e){onError(errorMessage(e));}}
  async function saveForm(){if(form.dataDir!==settings.dataDir&&!(await confirm('切换资料目录会打开该目录的资料库；当前资料不会自动搬迁。继续保存设置？')))return;await operation('保存设置',async()=>{await api.saveSettings({...form,setupComplete:true});await onSaved();setFeedback('设置已保存');});}
  async function probe(){if(changed){onError('请先保存新的配置，再检测识别环境。');return;}await operation('检测 CPU、显卡与识别环境',async()=>{setReport(await api.probeResources());setFeedback('环境检测已完成');});}
  async function download(){if(form.modelDir!==settings.modelDir){onError('请先保存模型目录，再开始下载。');return;}await operation(`下载并校验 ${form.model} 模型`,async()=>{await api.downloadModel(form.model);setReport(await api.probeResources());setCache(await api.cacheInventory());setFeedback('模型已下载并通过校验');});}
  async function benchmark(){if(changed){onError('请先保存配置，再验证这一组参数。');return;}if(!sample)return;await operation('正在转写样本前 60 秒',async()=>{const result=await api.benchmarkProfile(sample,form.model,form.device==='auto'?(actual.cudaAvailable?'cuda':'cpu'):form.device);setBenchmarks(await api.listBenchmarks());if(!result.success)onError(result.error??'样本验证未通过');else setFeedback('样本验证通过，实测记录已保存');});}
  async function clear(category:CacheCategory){if(!(await confirm(`清理“${category.title}”中的 ${bytesLabel(category.sizeBytes)} 缓存？${category.warning??'已有文字稿与笔记会保留。'}`)))return;await operation('清理缓存',async()=>{await api.clearCache(category.id);setCache(await api.cacheInventory());setFeedback('所选缓存已清理');await onSaved();});}
  async function saveKey(){await operation('保存密钥',async()=>{await api.setApiKey(key);setKey('');await onSaved();setFeedback('密钥已存入 Windows 凭据存储');});}
  async function clearKey(){if(!(await confirm('移除本应用保存的 API 密钥？已有资料与笔记会保留。')))return;await operation('移除密钥',async()=>{await api.setApiKey('');await onSaved();setFeedback('密钥已移除');});}
  const pathField=(field:keyof AppSettings,label:string,directory=false,hint?:string)=><label className="field" key={field}>{label}<div className="settings-path"><input value={String(form[field])} onChange={e=>update(field,e.target.value as never)} spellCheck={false}/><button aria-label={`选择${label}`} onClick={()=>void choose(field,directory)}><FolderOpen size={15}/></button></div>{hint&&<span className="hint">{hint}</span>}</label>;
  return <section className="page settings-page"><header className="page-heading"><div><span className="eyebrow">本地工作环境</span><h1>设置</h1><p>按你的硬件选择识别配置，随时调整资料与模型位置。</p></div><button className="primary" disabled={!!busy} onClick={()=>void saveForm()}><Save size={16}/>{changed?'保存修改':'保存设置'}</button></header>
    <div className="settings-tabs" role="tablist" aria-label="设置类别">{[['appearance','外观主题'],['storage','资料与工具'],['recognition','识别与资源'],['knowledge','知识整理 API'],['vault','Obsidian 知识库'],['cache','缓存管理']].map(([id,label])=><button role="tab" aria-selected={section===id} className={section===id?'active':''} onClick={()=>setSection(id)} key={id}>{label}</button>)}</div>
    {busy&&<div className="settings-progress"><Spinner label={busy}/><span className="hint">可继续查看其他设置，等待当前操作完成。</span></div>}{feedback&&<div className="settings-feedback"><CheckCircle2 size={16}/>{feedback}</div>}
    {section==='appearance'&&<div className="settings-section"><h2>背景与主题</h2><p className="hint">点击立即预览，保存设置后重启仍生效。放弃未保存修改会恢复原主题。</p><div className="theme-options">{themes.map(theme=><button key={theme.id} className="theme-option" disabled={!!busy} aria-pressed={form.theme===theme.id} onClick={()=>update('theme',theme.id)}><span className="theme-preview" style={{background:theme.background,color:theme.color}}>Aa · 课程</span><strong>{theme.name}</strong><small>{theme.description}</small></button>)}</div><p className="hint">主题同时应用于资料库、文字稿、笔记、设置与弹窗。</p></div>}
    {section==='storage'&&<div className="settings-columns"><div className="settings-section"><h2><HardDrive size={18}/>存储位置</h2><p className="hint">数据目录包含资料库、缓存、日志与导出文件。切换目录会切换资料库，文件不会自动移动。</p>{pathField('dataDir','资料目录',true)}{pathField('modelDir','Whisper 模型目录',true,'可选择已有模型目录，避免重复下载。外部共享目录不会被缓存清理删除。')}<button className="quiet" onClick={()=>void api.openDataFolder().catch(e=>onError(errorMessage(e)))}><FolderOpen size={15}/>打开当前资料目录</button></div>
      <div className="settings-section"><h2>处理工具</h2><p className="hint">选择已有可执行文件。仅导入字幕、校对和搜索无需安装识别环境。</p>{pathField('pythonPath','Python 识别环境',false,'需要 torch、openai-whisper、numpy；复用已验证的环境即可。')}{pathField('qualityPackagesDir','语音检测扩展目录（可选）',true,'复用上方 Python；仅语音检测加载此目录中的独立依赖，不修改原识别环境。')}{pathField('ffmpegPath','FFmpeg')}{pathField('ffprobePath','ffprobe')}{pathField('ytDlpPath','yt-dlp（可选）',false,'留空时使用上方 Python 环境中的 yt_dlp 模块。')}{pathField('cookieFile','网站 Cookie 文件（可选）',false,'Netscape 格式，按网站域名匹配，用于字幕与媒体请求。知识整理 API 不接收 Cookie。')}<button className="text-button" onClick={()=>void api.openExternal('https://github.com/jiashui2003/course-workbench#识别环境').catch(e=>onError(errorMessage(e)))}>查看识别环境配置说明<ExternalLink size={13}/></button></div></div>}
    {section==='recognition'&&<><div className="settings-resource"><div className="section-heading"><div><h2><Cpu size={18}/>本机资源</h2><p className="hint">候选建议来自能力检测；可用性仍需用实际音频试跑。</p></div><button disabled={!!busy} onClick={()=>void probe()}><RefreshCw size={15}/>重新检测</button></div><dl className="resource-list"><div><dt>CPU</dt><dd>{actual.cpuName.trim()} · {actual.logicalCores} 线程</dd></div><div><dt>内存</dt><dd>可用 {(actual.ramAvailableMb/1024).toFixed(1)} / {(actual.ramTotalMb/1024).toFixed(1)} GB</dd></div><div><dt>资料盘空间</dt><dd>{actual.diskFreeMb?(actual.diskFreeMb/1024).toFixed(1)+' GB 可用':'尚未获取'}</dd></div><div><dt>GPU</dt><dd>{actual.gpu?.name??'未检测到 NVIDIA GPU'}{actual.gpu&&<small>空闲 {actual.gpu.freeMb} / {actual.gpu.totalMb} MB · 驱动 {actual.gpu.driver}</small>}</dd></div><div><dt>识别后端</dt><dd>{actual.pythonAvailable?'Whisper 可用':'识别环境待配置'} · {actual.cudaAvailable?'CUDA 可用':'CPU 路径'}{actual.torchVersion&&<small>PyTorch {actual.torchVersion}</small>}</dd></div></dl>{actual.warnings.map((message,i)=><p className="hint settings-warning" key={i}>{message}</p>)}<div className="recommendation"><strong>当前建议：{choice.model} / {choice.device.toUpperCase()}</strong><p>{choice.reason}</p><span>这是候选配置，不表示已通过本机样本验证。</span></div></div>
      <div className="settings-columns"><div className="settings-section"><h2>识别配置</h2><label className="field">资源档位<select value={form.preset} onChange={e=>update('preset',e.target.value as AppSettings['preset'])}><option value="eco">省资源</option><option value="balanced">均衡（默认）</option><option value="quality">高质量</option><option value="custom">自定义模型与设备</option></select></label><p className="hint">前三档在任务创建时采用检测后的候选模型。更大的模型需要比较中文与术语表现。</p><label className="field">模型<select value={form.model} onChange={e=>setForm(current=>({...current,model:e.target.value,preset:'custom'}))}>{models.map(([model,size])=><option key={model} value={model}>{model} · {size}</option>)}{!models.some(([model])=>model===form.model)&&<option value={form.model}>{form.model}</option>}</select></label><div className="settings-inline"><label className="field">运行设备<select value={form.device} onChange={e=>setForm(current=>({...current,device:e.target.value as AppSettings['device'],preset:'custom'}))}><option value="auto">自动</option><option value="cuda">NVIDIA CUDA</option><option value="cpu">CPU</option></select></label><label className="field">CPU 线程数<input type="number" min={1} max={actual.logicalCores||256} value={form.threads} onChange={e=>setForm(current=>({...current,threads:Number(e.target.value),preset:'custom'}))}/></label></div><p className="hint">GPU 转写并发为 1。更高并发尚未通过验证，不按显存容量自动增加。</p><label className="field">识别语言<select value={form.language} onChange={e=>update('language',e.target.value)}><option value="zh">中文</option><option value="en">英语</option><option value="">自动检测</option></select></label><label className="field">术语提示（可选）<textarea rows={3} value={form.prompt} onChange={e=>update('prompt',e.target.value)} placeholder="课程中可能出现的专业术语，逗号分隔"/></label></div>
      <div className="settings-section"><h2>模型与样本验证</h2><p className="hint">模型首次使用前需要下载。切换模型会生成独立转写版本。</p><div className="model-download"><div><strong>{form.model}</strong><span>{models.find(([model])=>model===form.model)?.[1]??'大小由模型决定'} · 首次下载</span></div><button disabled={!!busy} onClick={()=>void download()}><Download size={15}/>下载模型</button></div>{report&&<p className="hint">已有模型：{report.models.map(model=>model.name).join('、')||'未找到模型文件'}</p>}<div className="benchmark-control"><h3>用 60 秒音频验证配置</h3><p className="hint">选择已有回听音频的课程，测试前 60 秒。记录速度和资源用量，不自动判断识别准确率。</p><label className="field">样本课程<select value={sample} onChange={e=>setSample(e.target.value)}><option value="">选择一条有回听音频的课程</option>{assets.filter(asset=>asset.audioPath).map(asset=><option key={asset.id} value={asset.id}>{asset.title}</option>)}</select></label><button disabled={!!busy||!sample} onClick={()=>void benchmark()}><FlaskConical size={15}/>验证当前模型与设备</button></div><div className="benchmark-list"><h3>实测记录</h3>{!benchmarks.length?<p className="hint">尚无本机实测记录。</p>:benchmarks.slice(0,12).map(run=><div key={run.id} className="benchmark-row"><div><strong>{run.model} / {run.device.toUpperCase()}</strong><span className={run.success?'passed':'failed'}>{run.success?'通过':'未通过'}</span></div><p>{run.audioSeconds.toFixed(0)} 秒音频 · {run.elapsedSeconds.toFixed(1)} 秒处理 · {run.threads} 线程</p>{run.success?<p>RAM {run.peakRamMb?.toFixed(0)??'—'} MB · 显存分配 {run.peakGpuMb?.toFixed(0)??'—'} MB</p>:<p className="error-text">{run.error}</p>}</div>)}<p className="hint">显存峰值来自 PyTorch 分配器，不等同于整张显卡的系统总占用。模拟设备不写入实测记录。</p></div></div></div></>}
    {section==='knowledge'&&<div className="settings-columns"><div className="settings-section"><h2>OpenAI 兼容文本接口</h2><p className="hint">生成笔记或问答时，只发送你选中的原文片段。兼容本机服务；本应用不安装本地大模型。</p><label className="field">API 地址<input value={form.llmBaseUrl} onChange={e=>update('llmBaseUrl',e.target.value)} placeholder="https://api.example.com/v1" spellCheck={false}/></label><label className="field">模型名称<input value={form.llmModel} onChange={e=>update('llmModel',e.target.value)} placeholder="填写服务商提供的模型名" spellCheck={false}/></label><label className="field">单次最多发送字符数<input type="number" min={1000} max={200000} step={1000} value={form.llmContextChars} onChange={e=>update('llmContextChars',Number(e.target.value))}/><span className="hint">选择超过上限时会提示缩小范围，不会偷偷截断原文。</span></label><button className="primary" disabled={!!busy} onClick={()=>void saveForm()}><Save size={15}/>保存 API 配置</button></div><div className="settings-section"><h2><KeyRound size={17}/>API 密钥</h2><p className="hint">密钥保存在 Windows 凭据存储，不写入资料库或设置文件。</p><p className="key-status">{apiKeyConfigured?<><CheckCircle2 size={15}/>已保存密钥</>:'尚未保存密钥；免密本机服务可留空。'}</p><label className="field">设置或替换密钥<input type="password" value={key} autoComplete="off" spellCheck={false} onChange={e=>setKey(e.target.value)} placeholder="输入新密钥"/></label><div className="actions"><button disabled={!!busy||!key.trim()} onClick={()=>void saveKey()}>保存密钥</button><button className="quiet" disabled={!!busy||!apiKeyConfigured} onClick={()=>void clearKey()}>移除密钥</button></div><div className="settings-note"><h3>先校对，再整理</h3><p>摘要与回答绑定生成时的文字版本。之后修订原文，旧笔记仍可追溯，并提示重新生成。</p><p>材料不足时，回答会明确说明，不将推测当作课程内容。</p></div></div></div>}
    {section==='vault'&&<div className="settings-section"><h2>Obsidian 本地知识库</h2><p className="hint">选择已有 vault，或填写一个新的独立文件夹（例如 D:\个人知识库）。保存设置后初始化，然后在 Obsidian 中将此文件夹作为仓库打开。</p>{pathField('obsidianVault','Obsidian 知识库目录',true,'只在 CourseWorkbench 子目录写入课程资料，不上传云端，不需要社区插件。')}<div className="actions"><button disabled={!!busy||changed||!settings.obsidianVault} onClick={()=>void operation('初始化知识库',async()=>{const root=await api.initializeVault();setFeedback(`知识库已就绪：${root}。在 Obsidian 中选择“打开文件夹作为仓库”，再从课程页面同步。`);})}>初始化 / 检查知识库</button><button onClick={()=>void api.openExternal('https://obsidian.md/download').catch(e=>onError(errorMessage(e)))}>Obsidian 官方下载</button></div>{changed&&<p className="hint">请先点击右上角保存设置。</p>}<div className="settings-note"><h3>同步与个人笔记</h3><p>在课程阅读页同步当前查看的已保存文字版本、引用笔记和完整性报告。重复同步相同内容不会重复创建；新内容生成新快照，保留历史引用。</p><p>请把自己的补充写到课程目录的“个人笔记.md”。同步不会覆盖这个文件。修改过的快照再次同步时会报冲突，原文件保留。</p><p>入口是 CourseWorkbench/课程索引.md。尚未安装 Obsidian 时，全部 Markdown 文件仍可用文本编辑器打开；音视频不会复制进知识库。</p></div></div>}
    {section==='cache' &&<div className="settings-section"><div className="section-heading"><div><h2>缓存用量</h2><p className="hint">按类别清理应用生成的文件。原始本地媒体、文字版本与学习笔记会保留。</p></div><button disabled={!!busy} onClick={()=>void operation('读取缓存用量',async()=>setCache(await api.cacheInventory()))}><RefreshCw size={15}/>刷新</button></div><div className="cache-list">{cache.map(category=><div className="cache-row" key={category.id}><div><h3>{category.title}</h3><p title={category.path}>{category.path}</p>{category.warning&&<span>{category.warning}</span>}</div><div className="cache-size"><strong>{bytesLabel(category.sizeBytes)}</strong><small>{category.fileCount} 个文件</small></div><button disabled={!!busy||!category.clearable||category.fileCount===0} onClick={()=>void clear(category)}><Trash2 size={14}/>清理</button></div>)}</div></div>}
    {dialog}
  </section>;
}
